CREATE TABLE CADASTRO
(CODCADASTRO INT,
NOME VARCHAR(40),
SEXO VARCHAR(20),
EMAIL VARCHAR(40),
LOGIN VARCHAR(10),
SENHA VARCHAR(20),
CONSTRAINT PK_CODCADASTRO PRIMARY KEY(CODCADASTRO));

SELECT*FROM CADASTRO